# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(924, 641)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabTokensTree = QtWidgets.QTabWidget(self.centralwidget)
        self.tabTokensTree.setMinimumSize(QtCore.QSize(450, 450))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabTokensTree.setFont(font)
        self.tabTokensTree.setObjectName("tabTokensTree")
        self.tabTokens = QtWidgets.QWidget()
        self.tabTokens.setObjectName("tabTokens")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabTokens)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tTokens = QtWidgets.QTableWidget(self.tabTokens)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.tTokens.setFont(font)
        self.tTokens.setObjectName("tTokens")
        self.tTokens.setColumnCount(0)
        self.tTokens.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tTokens)
        self.tabTokensTree.addTab(self.tabTokens, "")
        self.tabTree = QtWidgets.QWidget()
        self.tabTree.setObjectName("tabTree")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabTree)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.treeTree = QtWidgets.QTreeView(self.tabTree)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.treeTree.setFont(font)
        self.treeTree.setObjectName("treeTree")
        self.verticalLayout_3.addWidget(self.treeTree)
        self.tabTokensTree.addTab(self.tabTree, "")
        self.gridLayout.addWidget(self.tabTokensTree, 0, 0, 1, 1)
        self.tabCodeOutput = QtWidgets.QTabWidget(self.centralwidget)
        self.tabCodeOutput.setMinimumSize(QtCore.QSize(450, 450))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabCodeOutput.setFont(font)
        self.tabCodeOutput.setObjectName("tabCodeOutput")
        self.tabCode = QtWidgets.QWidget()
        self.tabCode.setObjectName("tabCode")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabCode)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.peCode = QtWidgets.QPlainTextEdit(self.tabCode)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.peCode.setFont(font)
        self.peCode.setObjectName("peCode")
        self.verticalLayout_4.addWidget(self.peCode)
        self.tabCodeOutput.addTab(self.tabCode, "")
        self.tabOutput = QtWidgets.QWidget()
        self.tabOutput.setObjectName("tabOutput")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabOutput)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.peOutput = QtWidgets.QPlainTextEdit(self.tabOutput)
        self.peOutput.setObjectName("peOutput")
        self.verticalLayout_5.addWidget(self.peOutput)
        self.tabCodeOutput.addTab(self.tabOutput, "")
        self.gridLayout.addWidget(self.tabCodeOutput, 0, 1, 1, 1)
        self.gbLog = QtWidgets.QGroupBox(self.centralwidget)
        self.gbLog.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.gbLog.setFont(font)
        self.gbLog.setObjectName("gbLog")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gbLog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.peLog = QtWidgets.QPlainTextEdit(self.gbLog)
        self.peLog.setObjectName("peLog")
        self.verticalLayout.addWidget(self.peLog)
        self.gridLayout.addWidget(self.gbLog, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 924, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAnalyze = QtWidgets.QMenu(self.menubar)
        self.menuAnalyze.setObjectName("menuAnalyze")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_file = QtWidgets.QAction(MainWindow)
        self.actionSave_file.setObjectName("actionSave_file")
        self.actionOpen_file = QtWidgets.QAction(MainWindow)
        self.actionOpen_file.setObjectName("actionOpen_file")
        self.actionAnalyze = QtWidgets.QAction(MainWindow)
        self.actionAnalyze.setObjectName("actionAnalyze")
        self.menuFile.addAction(self.actionSave_file)
        self.menuFile.addAction(self.actionOpen_file)
        self.menuAnalyze.addAction(self.actionAnalyze)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAnalyze.menuAction())

        self.retranslateUi(MainWindow)
        self.tabTokensTree.setCurrentIndex(1)
        self.tabCodeOutput.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python Parser with PLY"))
        self.tabTokensTree.setTabText(self.tabTokensTree.indexOf(self.tabTokens), _translate("MainWindow", "Tokens"))
        self.tabTokensTree.setTabText(self.tabTokensTree.indexOf(self.tabTree), _translate("MainWindow", "Tree"))
        self.tabCodeOutput.setTabText(self.tabCodeOutput.indexOf(self.tabCode), _translate("MainWindow", "Code"))
        self.tabCodeOutput.setTabText(self.tabCodeOutput.indexOf(self.tabOutput), _translate("MainWindow", "Output"))
        self.gbLog.setTitle(_translate("MainWindow", "Log"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAnalyze.setTitle(_translate("MainWindow", "Analisys"))
        self.actionSave_file.setText(_translate("MainWindow", "Save file"))
        self.actionOpen_file.setText(_translate("MainWindow", "Open file"))
        self.actionAnalyze.setText(_translate("MainWindow", "Analyze"))

