sudo: required
language: python
python:
  - '3.6'
install:
  - pip install -r requirements.txt
script:
  - python -m unittest regexequationset/nfaregexp/tests.py
  - python -m unittest grammar/test.py