sudo: required
language: python
python:
  - '3.6'
install:
  - pip install -r requirements.txt
script:
  - cd regexequationset
  - python -m unittest test.py
  - cd ../grammars/grammar
  - python -m unittest test.py